name: Renewal

on:
  push: 
    branches: [main]
  schedule:
    - cron: '0 8 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
          repository: 'mkorthof/freenom-script'
      - name: Install freenom-script
        run: sudo make install
      - name: Configure freenom-script
        run: |
          sudo rm -f /usr/local/etc/freenom.conf
          sudo wget ${{ secrets.link }} -O /usr/local/etc/freenom.conf &> /dev/null
      - name: random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-1800 -n 1)
      - name: run script
        run: sudo freenom.sh -r -a -o
